// Code generated by "stringer -type=NodeType,Token -output=stringer.go"; DO NOT EDIT

package main

import "fmt"

const _NodeType_name = "NCommandNPipeNRedirectionNBackgroundNSubshellNAndNOrNSemicolonNIfNWhileNUntilNForNCaseNFunctionNArgNRedirToNRedirAppendNRedirClobberNNot"

var _NodeType_index = [...]uint8{0, 8, 13, 25, 36, 45, 49, 52, 62, 65, 71, 77, 81, 86, 95, 99, 107, 119, 132, 136}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return fmt.Sprintf("NodeType(%d)", i)
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}

const _Token_name = "TEOFTNewLineTSemicolonTBackgroundTAndTOrTPipeTLeftParenTRightParenTEndCaseTEndBackQuoteTRedirectionTWordTNotTCaseTDoTDoneTElifTElseTEsacTFiTForTIfTInTThenTUntilTWhileTBeginTEnd"

var _Token_index = [...]uint8{0, 4, 12, 22, 33, 37, 40, 45, 55, 66, 74, 87, 99, 104, 108, 113, 116, 121, 126, 131, 136, 139, 143, 146, 149, 154, 160, 166, 172, 176}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
