// Code generated by "stringer -type=Token"; DO NOT EDIT

package main

import "fmt"

const _Token_name = "TEOFTNewLineTSemicolonTBackgroundTAndTOrTPipeTLeftParenTRightParenTEndCaseTEndBackQuoteTRedirectionTWordTNotTCaseTDoTDoneTElifTElseTEsacTFiTForTIfTInTThenTUntilTWhileTBeginTEnd"

var _Token_index = [...]uint8{0, 4, 12, 22, 33, 37, 40, 45, 55, 66, 74, 87, 99, 104, 108, 113, 116, 121, 126, 131, 136, 139, 143, 146, 149, 154, 160, 166, 172, 176}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
