// Code generated by "stringer -type=Token"; DO NOT EDIT

package arith

import "fmt"

const _Token_name = "ArithErrorArithAssignmentArithNotArithAndArithOrArithNumberArithVariableArithLessEqualArithGreaterEqualArithLessThanArithGreaterThanArithEqualArithNotEqualArithBinaryAndArithBinaryOrArithBinaryXorArithLeftShiftArithRightShiftArithRemainderArithMultiplyArithDivideArithSubtractArithAddArithAssignBinaryAndArithAssignBinaryOrArithAssignBinaryXorArithAssignLeftShiftArithAssignRightShiftArithAssignRemainderArithAssignMultiplyArithAssignDivideArithAssignSubtractArithAssignAddArithLeftParenArithRightParenArithBinaryNotArithQuestionMarkArithColonArithEOF"

var _Token_index = [...]uint16{0, 10, 25, 33, 41, 48, 59, 72, 86, 103, 116, 132, 142, 155, 169, 182, 196, 210, 225, 239, 252, 263, 276, 284, 304, 323, 343, 363, 384, 404, 423, 440, 459, 473, 487, 502, 516, 533, 543, 551}

func (i Token) String() string {
	i -= 1
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i+1)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
